# Generated by Django 6.0.3 on 2026-03-22 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название баннера')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='Слоган баннера')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('link_url', models.URLField(max_length=500, verbose_name='Ссылка перенаправления')),
                ('image', models.ImageField(upload_to='images/banners/', verbose_name='Изображение баннера')),
                ('is_active', models.BooleanField(default=False, verbose_name='Видимость баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
