# Generated by Django 6.0.3 on 2026-03-22 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='Слоган баннера')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Название подсекции')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='GymActivities/', verbose_name='Изображение')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Активность в зале',
                'verbose_name_plural': 'Активности в зале',
            },
        ),
    ]
