# Generated by Django 6.0.3 on 2026-03-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0002_gymactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(max_length=50, verbose_name='Якорь - Ссылка перенаправления'),
        ),
        migrations.AlterField(
            model_name='gymactivity',
            name='link_url',
            field=models.CharField(default='', max_length=50, verbose_name='Якорь - Ссылка перенаправления'),
            preserve_default=False,
        ),
    ]
