# Generated by Django 6.0.3 on 2026-03-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0003_alter_banner_link_url_alter_gymactivity_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(max_length=50, verbose_name='Выбираемая ссылка'),
        ),
    ]
