# Generated by Django 6.0.3 on 2026-03-23 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0004_alter_banner_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/PhotoAlbumCovers/', verbose_name='Обложка альбома')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['-created_at'],
            },
        ),
    ]
