# Generated by Django 6.0.3 on 2026-03-23 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0005_photoalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID для фото')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок фото')),
                ('image', models.ImageField(upload_to='images/ImageGallery/', verbose_name='Фотография')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория/Тег')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать в галерее')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='managementsystem.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея изображений',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
