# Generated by Django 6.0.3 on 2026-03-25 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0006_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость (руб.)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность (в днях)')),
                ('is_highlighted', models.BooleanField(default=True, verbose_name='Подсвеченный тариф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['price'],
            },
        ),
    ]
