# Generated by Django 6.0.3 on 2026-03-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0007_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Услуга тарифного плана',
                'verbose_name_plural': 'Услуги тарифного плана',
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='managementsystem.subscriptionplanfeature', verbose_name='Включенные услуги'),
        ),
    ]
