# Generated by Django 6.0.3 on 2026-03-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0009_alter_subscriptionplan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='managementsystem.subscriptionplanfeature', verbose_name='Включенные услуги'),
        ),
    ]
